#!/bin/sh

PL_QUESTION_PATH=/Users/christinayang/Documents/GitHub/OPB/pl-opb-ind100/questions/FM
CHECKQ=/Users/christinayang/Documents/GitHub/OPB/instructor_stats_bank/scripts/checkq.py
WRITE_PATH=/Users/christinayang/Documents/GitHub/OPB/instructor_stats_bank/source/unsorted

LINK=https://ca.prairielearn.com/pl/course_instance/4024/instructor/course_admin/questions

# opb-utils/questions/q03_data_basics/q03_data_basics.md
# git clone https://github.com/open-resources/instructor_physics_bank.git
FILE=questions/$1/$1.md;
cd /Users/christinayang/Documents/GitHub/OPB/instructor_stats_bank
git reset --hard origin/main
echo $FILE
out="$(basename $FILE .md)"
BRANCH_NAME="$(basename $FILE .md)"
TITLE=$2
ASSIGN=$3
echo $BRANCH_NAME
git checkout -B $BRANCH_NAME
cp -R /Users/christinayang/Documents/GitHub/OPB/opb-utils/questions/$out $WRITE_PATH
echo "ADDING $WRITE_PATH/$out"
git add $WRITE_PATH/$out
git commit -m "Autogenerated template"
git push --force-with-lease -u origin $BRANCH_NAME
echo "PUSHED $FILE SUCCESSFULLY"
ISSUES=
MESSAGE=""
shift 3
for var in "$@"
do
    MESSAGE+="Resolves #$var, "
done
MESSAGE=${MESSAGE%?}
MESSAGE=${MESSAGE%?}
echo $MESSAGE
gh pr create --draft -t "$BRANCH_NAME" -b $MESSAGE -b "OPB 000: $LINK, Title: $TITLE" --assignee $ASSIGN
